### PR TITLE
allow functions and regexps in patterns array

### PR DESCRIPTION
**Pull request by timkendrick**
How about allowing filter functions and regular expressions in the `patterns` array?

No worries if you feel this complicates things too much.

### CODE REVIEW

**Comment by welcoMattic** [comment]
LGTM! It's gonna be cool with function support

**Comment by timkendrick** [comment]
Did you get a chance to take a look at this, @sindresorhus? Let me know if there's any changes I can make.

**Comment by arthurvr** [comment]
> How about allowing filter functions and regular expressions in the patterns array?

I would personally prefer this module to stay minimal.

**Comment by sindresorhus** [comment]
Yeah, too much for this module. I'd suggest you just make a module that depends on this one.

**Comment by timkendrick** [comment]
OK will do, thanks for the advice!

**Pull request closed without merging**
